# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Engineer_AI_Disha_Shekhat_Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'Alamofire'
	pod 'SVProgressHUD'
  # Pods for Engineer_AI_Disha_Shekhat_Test

end
